### ISSUE TITLE
Not compatible with node-opcua 2.0.0

### ISSUE THREAD

**Issue by mstfldmr** [node-opcua/node-opcua-sample#4]
This sample code is not valid with newer versions of node-opcua.

**Comment by popolla** [comment]
That's true. First, it should use `OPCUAClient.create` instead of `new OPCUAClient`.
Second, in the readme I'd recommend using option `--unsafe-perm=true` when installing globally on Ubuntu via npm, in order to avoid possible certificate creation errors.
Last, the name of the ECMAScript 2017 example (`simple_client_es8.js`) is incorrect in the readme.

**Comment by erossignon** [comment]
Thank you for spotting this, this repo is unfortunately not updated on a regular basis,
Examples have been adjusted
